version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping deployment package..."
      - ls -la
      - zip lambda-node.zip calculate.js
      - ls -la
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name NodeSecrets --zip-file fileb://lambda-node.zip
      - echo "DONE!!"